### ISSUE TITLE
websocket is disconnected: Invalid HTTP upgrade

### ISSUE THREAD

**Issue by LamourBt** [daltoniam/Starscream#163]
I am using the pod 1.1.1, in addition I set up the localhost with MAMP and change the port to 8080, so the idea is to ran the "SimpleTest" but as I run the program the console message only said "Invalid HTTP upgrade"

and also when I ran this command on the terminal ruby ws-server.rb, I had this error:
 ws-server.rb:5: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
ws-server.rb:6: syntax error, unexpected '<'
<html lang="en" class=" is-copy-enabled is-u2f-enabled">
 ^
ws-server.rb:6: syntax error, unexpected keyword_class, expecting end-of-input
<html lang="en" class=" is-copy-enabled is-u2f-enabled">

Can someone help me please ?

**Comment by acmacalister** [comment]
Ok... I'm not sure what you are trying to do. The Simple Test project works fine for me. Here are a few things to review.

1. From my understanding MAMP doesn't support WebSockets. That is probably why you are getting `Invalid HTTP upgrade` as default MAMP doesn't know anything about the WebSocket protocol. Apache has be configured to forward WebSocket connections and the backend PHP app has to upgrade the connection using some sort of WebSocket server library (just like ws-server.rb has).

2. I'm not sure how you are getting the `ws-server.rb` Are you trying to send html over the WebSocket connection or is something else bound on port 8080? the ws-server.rb is a self hosted WebSocket server and just following the instructions in the README should get SimpleTest working without an issue.

**Comment by LamourBt** [comment]
Yeah If I fixed it... the thing was that MAMP was interfering with the connection and I had to shut it down. However I am new to web socket .. do you think i could you parse cloud to host my server ? Or if you know any server service company I could use.

**Comment by acmacalister** [comment]
Probably don't want to use Parse since it appears they are shutting down now.

http://blog.parse.com/announcements/moving-on/

If you are looking for hosted WebSockets you could setup a WebSocket server in your favorite language on Heroku or as you said setup your on server any of the cloud providers. There is also Pusher which uses WebSockets under the covers. 

https://pusher.com

There Swift client library appears to use Starscream as well. 

https://github.com/pusher/pusher-websocket-swift

Lots of great options, just have to decide what works for you. :smile:
