### ISSUE TITLE
How can I switch between different URLs and connect to them?

### ISSUE THREAD

**Issue by Tachines** [daltoniam/Starscream#212]
I'm new to iOS development, and I want to modify the example provided. What I want to do is that when use launch the app, there is text field where I can input URL manually. Here is my code:

`var defUrl = ""
class ViewController: UIViewController, WebSocketDelegate {
    @IBOutlet weak var urlText: UITextField! // Input from text field

    @IBAction func changeUrl(sender: AnyObject) {
        defUrl = urlText.text!
    }
    var socket = WebSocket(url: NSURL(string: defUrl)!)
    
    override func viewDidLoad() {
        super.viewDidLoad()
        socket.delegate = self
    }
    @IBAction func connect(sender: UIButton) {
        socket.connect()
    ...
    ... 
`
But it doesn't work, error message is: "fatal error: unexpectedly found nil while unwrapping an Optional value".

**Comment by daltoniam** [comment]
This isn't a issue with Starscream, but rather a general Swift question which is somewhat outside of the scope of a github issue. In any case, the issue is your are explicitly unwrapping the URL object and thus causing a crash (that is what the !` does). If the NSURL isn't valid it will return nil, and since you are force unwrapping the optional NSURL it crashes. For example, say you enter hello.com, which isn't a valid url since it doesn't have a scheme (http:// ) the NSURL will fail to initialize and the force unwrapping crashes it. Also you need to change your socket object to be created when you update your url.

```swift
var socket: WebSocket? (url: NSURL(string: "http://availdurl.com")!)

@IBAction func changeUrl(sender: AnyObject) {
guard let text = urlText.text else {return}
guard let url = NSURL(string: text) else {return}
socket = WebSocket(url: url)
socket.delegate = self
}

override func viewDidLoad() {
    super.viewDidLoad()
    //not here, doesn't work for your setup
}
@IBAction func connect(sender: UIButton) {
    socket?.connect()
...
...
```

If you have any more questions, I would refer the the Swift book on how optionals work. 

https://itunes.apple.com/us/book/swift-programming-language/id881256329?mt=11
