### ISSUE TITLE
Crash EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by lucatorella** [daltoniam/Starscream#221]
Just got this crash from Crashlytics, unfortunately I don't know how to reproduce it, and the stack trace doesn't seem so useful. Any idea?

```
Crashed: com.vluxe.starscream.websocket
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x61746572809a57f1

0  libobjc.A.dylib                0x181c49b9c objc_msgSend + 28
1  CoreFoundation                 0x18257a25c _inputStreamCallbackFunc + 56
2  CoreFoundation                 0x182521bc0 _signalEventSync + 192
3  CoreFoundation                 0x1825960a4 ___signalEventQueue_block_invoke + 24
4  libdispatch.dylib              0x18201d4bc _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x18201d47c _dispatch_client_callout + 16
6  libdispatch.dylib              0x1820294c0 _dispatch_queue_drain + 864
7  libdispatch.dylib              0x182020f80 _dispatch_queue_invoke + 464
8  libdispatch.dylib              0x18202b390 _dispatch_root_queue_drain + 728
9  libdispatch.dylib              0x18202b0b0 _dispatch_worker_thread3 + 112
10 libsystem_pthread.dylib        0x182235470 _pthread_wqthread + 1092
11 libsystem_pthread.dylib        0x182235020 start_wqthread + 4
```

**Comment by daltoniam** [comment]
Yeah that is pretty ambiguous 😞. It appears to be a crash when the dispatch callback is run by NSStream. It really could be anything crashing the application and the WebSocket object is causing the crash because it thinks the WebSocket object is valid and it isn't. I would check for race conditions to the WebSocket object as Starscream isn't "thread safe" and shouldn't be called from multiple threads. Also I would check and ensure the WebSocket isn't getting over released and a zombie as that could cause this too. I know those are pretty broad suggestions, but unfortunately we don't have much to go off. Best of luck!
