### ISSUE TITLE
RCV and masked data error

### ISSUE THREAD

**Issue by kojiba** [daltoniam/Starscream#251]
Hi, guys, a debugged some and I think, that somewhere is logic error.
I see dat normal http message processing like raw

message:
"HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: ZsqtHP56BomqoBGI7fsS/AO2fNU=\r\n\r\n"

logic:
(RSVMask & baseAddress[0]) > 0
always will be true, cause the first byte is ascii 'H' = 0x48
i.e. 0x48 & 0x70 always will be > 0, and 
if (isMasked > 0 || (RSVMask & baseAddress[0]) > 0) always will be true, even if isMasked = false

please, check dat code, I think the issue with masked data is not fixed

**Comment by kojiba** [comment]
I.e. I think you need create and error that indicates "Raw HTTP in websocket connection"

**Comment by daltoniam** [comment]
I'm not really sure what you are seeing or what you mean. The initial HTTP upgrade and switching protocols stuff doesn't fall into the WebSocket packet parsing. It first falls into:

https://github.com/daltoniam/Starscream/blob/master/Source/WebSocket.swift#L488

Where it handles switching from HTTP to WebSockets. Can you provide anymore details?

**Comment by kojiba** [comment]
I have a bug when firstly send a raw data, then backend send innormously a raw http (i.e. it is a backend error), but it can be indicated.

**Comment by daltoniam** [comment]
The raw HTTP in a WebSocket connection is basically the same as getting a malformed WebSocket packet. There isn't an simple way to detect what "kind" of malformed packet and the error reporting on what it knows. I don't think a change is necessary as it is properly falling into an error state even if the message is less than ideal due to the variable nature of a malformed packet.
