### ISSUE TITLE
websocketDidReceiveMessage not being called

### ISSUE THREAD

**Issue by kellyaltom** [daltoniam/Starscream#274]
websocketDidReceiveMessage is only being called on disconnect.

My app is receiving data from the websocket connection but the call to didreceivemessage is being skipped over and I am not sure why.

stepping through the code this method is called when text comes back over the websocket:
private func processResponse(_ response: WSResponse)

And then this code in processResponse fails:

if canDispatch {
                    callbackQueue.async { [weak self] in
                        guard let s = self else { return }
                        s.onText?(str! as String)
                        s.delegate?.websocketDidReceiveMessage(socket: s, text: str! as String)
                    }
                }

canDispatch evaluates to true but then the "callbackQueue.async" fails and skips over the call to websocketDidReceiveMessage.

If I let this continue until disconnect then websocketDidReceiveMessage is called and all of the data appears.

I can't figure out what is happening in processResponse(). Any help is appreciated.

**Comment by daltoniam** [comment]
hm, not sure what would cause the callbackQueue to fail since that is normally set to to the main dispatch queue (main thread). Everything seems to be working in my tests. Are you using a custom queue or something? I also release a new 2.0.1 which you might want to try (did change anything specific for this, but worth trying)

**Comment by kellyaltom** [comment]
Thanks I will give the the release a try.
Do you know if using usleep() could cause a main thread issue? I read that using sleep can cause a problem but I have not read anything about using usleep()

**Comment by acmacalister** [comment]
`usleep` inside of Starscream probably isn't causing issues with the delegate not getting called. You are correct that in general that `sleep` can block your main thread, but in our case the `sleep` is just used on a background thread for a deterministic amount of time, which should be fine.

**Comment by kellyaltom** [comment]
Thanks, for your reply.


I am still working through this issue. Here is a post from the apple forum: https://forums.developer.apple.com/message/193566#193566


I am streaming audio data over the websocket and data is coming back and then processResponse func is being called and the call to didreceivemessage is being put onto the mainqueue but the code does not execute until disconnect is called.


The code I am using worked fine before swift 3.  I am working on a new app and I reused the code that worked before in a previous app.


I was reading this about the queues in swift 3 - https://medium.com/swift-and-ios-writing/a-quick-look-at-gcd-and-swift-3-732bef6e1838#.prn1psouf


and wondering if a queue attribute could be used to get the code to execute while data is being sent and received.





________________________________

**Comment by acmacalister** [comment]
@kellyaltom I read over your issue on the Apple Forum. It sounds like something is block your main thread and preventing you from getting the delegate callbacks, but there isn't much to go off. We haven't heard anyone having this issue with Starscream on Swift 3 and in our test projects the callbacks fire just fine. If you can share your code or have a stripped down version that is able to replicate the problem, I can help you. Since I can't reproduce the problems and others aren't having the issue, it stands reason it is probably not a Swift 3 issue and more likely something in your setup.

**Comment by kellyaltom** [comment]
Thanks Ausitn, I will work through the main thread stack and see if I can discover the problem. If I can't I will share my app with you and will appreciate your help.


Thanks,

Kelly


________________________________

**Comment by kellyaltom** [comment]
I found the problem.

websocketdidconnect was running on the main thread and I was sending data from inside websocketdidconnect. I put the section of code that was sending data onto DispatchQueue.global and it now works as expected.


Thanks


________________________________

**Comment by acmacalister** [comment]
Glad you got it figured out! Also remember run it on a custom queue as well.

https://github.com/daltoniam/Starscream#custom-queue
