### ISSUE TITLE
timeout not obeyed?

### ISSUE THREAD

**Issue by kostasv4** [daltoniam/Starscream#306]
Hello there,

I'm using Starscream and overall it is amazing but I'm having a hard time with the connection timeout.

I define the socket as:

        let thisURL = NSURLComponents()
        thisURL.scheme = "wss"
        thisURL.host = strIP.trimmingCharacters(in: .whitespaces)
        thisURL.port = Int(strPort.trimmingCharacters(in: .whitespaces)) as NSNumber?
        thisURL.path = "/"

        let socket = WebSocket(url: thisURL.url!, protocols: ["test"])
        socket.selfSignedSSL = true
        socket.timeout = 2
        
        socket.delegate = self

        print( NSDate() )
        socket.connect()

and in the websocketDidDisconnect function I've put another print of the NSDate() and what I get is a difference of about 8-9sec when I try to use a host that exists but of course is not configured for my app, for example www.google.com with port 80. There are 3 sets of results as a re-try 3 times before aborting...

The results I see are:
2017-01-29 19:43:17 +0000
2017-01-29 19:43:25 +0000

not connected, retrying...
2017-01-29 19:43:25 +0000
2017-01-29 19:43:33 +0000

not connected, retrying...
2017-01-29 19:43:33 +0000
2017-01-29 19:43:42 +0000

Any way I can 'enforce' the timeout?

Thanks!

**Comment by daltoniam** [comment]
The timeout should internally work somewhat close to the timeout point. `google.com` isn't a web socket server so it might be failing to do anything (I don't know how google handles random web socket upgrade commands). Also something to note is using the delegate methods to log might not give exact 2 second timeout because there is a background thread and messages get sent to the main dispatch queue to get run. There could be some variable time in that coming back because it is going from one queue/thread to another and has to awaits its turn. Also from the code the 2 seconds the first print is right before the socket connects, so there is the socket connection time to roll into that time slice. 

It summary, the timeout is probably working fine and this would be the expected behavior. I hope that helps clear this up, best of luck.
