### ISSUE TITLE
Export Compliance and Starscream

### ISSUE THREAD

**Issue by murphman300** [daltoniam/Starscream#379]
Hello guys,

Just wondering if Starscream falls under Apple-covered export compliance, or if it requires additional paperwork? I'm planning on building out a socket client around Starscream for a financial information endpoint.

Thanks for the good work!

cheers

**Comment by acmacalister** [comment]
Good question. I'm not totally sure I'm qualified to answer this, but I would assume that would fall under the Apple covered exported compliance, since it uses all Apple cryptography APIs. That being said, we have never done an audit on the code (and probably never will), so I would check with a legal team if that is hard requirement.
