### ISSUE TITLE
Missing required modules: SSCZLib, SSCommonCrypto

### ISSUE THREAD

**Issue by d-theo** [daltoniam/Starscream#406]
Hi,
I am distributing an already compiled framework that uses SocketIO/Starscream to clients , do you know if this is possible ? Right now i'm getting the error :

> Missing required modules: SSCZLib, SSCommonCrypto

Is there any workaround ? (actually the only thing I found would be to ask the client to include the `zlib` directory into their **Build Settings->import Paths** but it's not really usable for production).

best regards

**Comment by daltoniam** [comment]
Are you including the `module.modulemap` and `include.h` in your compiled framework? That is way it can reference those frameworks in the import. Also you will have to require that the clients also link with the `CommonCrypto` and `zlib` since Starscream needs those to do compression and a sha1 key thing.

It is going to have to be a configuration thing, but I'm not an expert on how compiled frameworks, so I don't have any recommendations on how to configure a framework to include this without asking the client to change their build settings. I believe it is fairly common to see third party frameworks require a little bit of configuration when including their framework (unless you use a package manager like CocoaPods or Swift Package Manager).

**Comment by d-theo** [comment]
It seems to works well with cocoapods/carthage because the client is compiling by himself.
I guess I will go with the **import Paths** solution :)
Thanks

**Comment by stonedauwg** [comment]
I also got this error just using Carthage and compiling my app (not a framework, regular iOS app target) against the carthage-built Starscream framework. Why do we have to include the zlib folder from the Carthage checkouts folder? Is there another alternative? I've never experienced having to do this with other carthage frameworks so curious why this is necessary
