### ISSUE TITLE
websocket is disconnected: Optional("Invalid HTTP upgrade") , Swift 4 & XCode 9.1

### ISSUE THREAD

**Issue by shobhakartiwari** [daltoniam/Starscream#427]
I am currently working in XCode 9.1 and iOS 11 , i am getting this error .
Startscream Pod version  : 3.0.2 .

Kindly suggest , i gone through the already raised issue on same topic in 2015 but its not working .

Kindly provide your suggestion , i am waiting for your response .

Thanks

**Comment by wosxieez** [comment]
i am also waiting for your response . tks.....

**Comment by shobhakartiwari** [comment]
Still waiting for response from Starscream

**Comment by daltoniam** [comment]
That is a fairly generic error of a WebSocket failing to upgrade. It is normally caused by a HTTP or WebSocket server rejecting the connection for not meeting some criteria it expected. Unfortunately I can't provided anymore information then that, but I can say it mostly likely isn't an issue with Starscream but rather an environment specific issue. Best of luck!
