### ISSUE TITLE
Firebase performance monitoring

### ISSUE THREAD

**Issue by jpm-polymorph** [daltoniam/Starscream#440]
On Firebase there is a `Performance - Network Requests` section that monitors the successes and failures of network requests. Is it possible to monitor Starscream websockets using Firebase? Does anyone have a suggestion how to do this?

**Comment by daltoniam** [comment]
I don't know of anyway to get Firebase monitoring to work. I took a *really* brief look at the docs and I'm going to guess they are hooking into NSURLSession to monitor HTTP requests (probably with method Swizzling?). Anyway, I don't think there is an easy way to get that to work with Starscream and the NSStream API without some custom code. Also the SDK appears to be design around the idea of an HTTP request/response cycle instead of a long lived connection like a WebSocket, so I'm doubtful on it working without some updates to the Firebase SDK. All that being said, that is just my guess and it might be worth asking someone at Firebase.
