### ISSUE TITLE
kCFErrorDomainCFNetwork error -72000 on physical watch but works on simulator?

### ISSUE THREAD

**Issue by sarcasticposhy** [daltoniam/Starscream#441]
I dont know if the problem lies with me but when i try to do this:
```
let request = URLRequest(url: URL(string: "<mywebsocketurl>")!)
socket = WebSocket(request: request)
socket.delegate = self
socket.connect()
```

my function websocketDidDisconnect() gets triggered and the error being kCFErrorDomainCFNetwork error -72000. 

This error is only appearing on my physical watch though, on the simulator it can connect and receive messages without any problem.

Any advice?

**Comment by daltoniam** [comment]
I unfortunately can't provide any assistance with the information provided. I don't know what the error code means. I'd definitely look at some kind of configuration issue like maybe you are using a local address URL (e.g. localhost or a local IP) instead of a WebSocket url that a physical watch can resolve?  That would be more only general suggestions with the information provided. Best of luck!
