### ISSUE TITLE
When using Starscream via Carthage, projects must also include zlib folder

### ISSUE THREAD

**Issue by iOSGeekster** [daltoniam/Starscream#445]
When including Starscream with Carthage, project can compile properly, as long as Starscream/zlib resides in Carthage/Checkouts. This should not be the case. So projects that includes Starscream should copy the zlib folder to the project dir, and add it to "Swift compiler - Search Path" in Build Settings.
I think the readme should reflect that?

**Comment by daltoniam** [comment]
I don't think you should have to do that if I understand how Carthage works properly. I'll admit my knowledge of Carthage is limited, but I thought the Cartfile and such would handle the dependencies?

**Comment by rastersize** [comment]
@daltoniam Carthage will “only” resolve and download (and build if there’s a framework target)  dependencies. Carthage won’t link the dependencies or add them to any Xcode project automatically.

So the modules downloaded by Carthage are actually redundant. Since Starscream isn’t using them for its framework target from what I can tell. I’d recommend removing the `Cartfile` all-together to be honest. Unless you intend to use it as the tool to pull in those dependencies for Starscream itself?

The same seems to apply to the SPM setup. Since Starscream is using [the modulemap in the bundled `zlib/` directory](https://github.com/daltoniam/Starscream/blob/master/zlib/module.modulemap). This is configured via `SWIFT_INCLUDE_PATHS = $SRCROOT/zlib`.

As it is right now the Cartfile results in a perpetually dirty repository for Carthage users. As Carthage creates `Carthage/{Checkouts,Build}/` directories that aren’t in your `.gitignore`. For now the way I’m handling that is after Carthage is done I run a cleanup job which basically executes `rm -r Carthage/Checkouts/Starscream/Carthage`.

To be honest I think bundling the module map as a single file is the best course of action. Even though it sometimes messes up LLDB (¯\\\_(ツ)_/¯).

**Comment by rastersize** [comment]
I made a small [example repo](https://github.com/rastersize/StarscreamViaCarthage) showcasing that the Carthage dependencies aren’t needed. As well as how Carthage works and how to integrate Starscream via Carthage.

The [`master` branch](https://github.com/rastersize/StarscreamViaCarthage/tree/master) contains a bare-bone project, Starscream pulled in via Carthage. The dependencies pulled in by Starscream via Carthage have been removed.

The [`with-zlib-cc-spm` branch](https://github.com/rastersize/StarscreamViaCarthage/tree/with-zlib-cc-spm) contains the same code except the `Carthage/Checkouts` directory in `Carthage/Checkouts/Starscream/` has not been removed. This is mostly just as a reference.

**Comment by acmacalister** [comment]
I think #461 should address this issue. If you could try it out of master and see if works, that would great!

**Comment by codeOfRobin** [comment]
@acmacalister Doesn't look like it worked for me 😕

**Comment by optikfluffel** [comment]
@acmacalister @codeOfRobin I just deleted the `Carthage/Checkouts/Starscream/zlib` folder and I'm not sure it's all working yet (sorry, new to Swift and Xcode xD) but at least it builds.

**Comment by Bersaelor** [comment]
I detailed what worked for my project [here](https://github.com/daltoniam/Starscream/issues/486#issuecomment-377763057) :

After every carthage update we delete the SSCZLib and SSCommonCrypto modulemap entries in
./Carthage/Checkouts/SwiftPhoenixClient/Example/Pods/Starscream/zlib.

Also we added $(SRCROOT)/Carthage/Checkouts/Starscream/zlib/ under Swift Compiler - Search Paths -> Import Paths in the Project Build Settings.

**Comment by bayareahank** [comment]
@Bersaelor  Thanks, the hack made my code run again, after blocked by this bug for several months. 

One question though, what purpose does the last step serve, can it be skipped? I run the code under Xcode 9.3 without the last step, it seems to be fine so far. 

Thanks again.

**Comment by fassko** [comment]
Please check with 3.0.6 version.
