### ISSUE TITLE
Keep Websocket Connection open while App is in Background Mode

### ISSUE THREAD

**Issue by sarcasticposhy** [daltoniam/Starscream#455]
As the title says, how am I able to keep the connection open and receive messages even when the app is in the background? Because now, everytime i set it to background or i lock my iPhone and unlock it, the websocket gets disconnected.

I've already found a solution and it says i should enable Voip in my Info.plist and then just do `socket.voipEnabled = true`, but it then says that Websocket does not have the member voipEnabled.

Does anyone have a quick example on how to run Websocket in background?

Thanks in advance

**Comment by jcislinsky** [comment]
+1

**Comment by texasexile** [comment]
You won't be able to keep sockets open in the background. I use sockets to deliver messages from a server. When the app comes back to foreground, I ask the server to catch up on messages sent since the last message.

You can also use push notifications if you need to deliver messages when the app is in the background.

**Comment by acmacalister** [comment]
@texasexile is correct. See issue #309 for more information on this.
