### ISSUE TITLE
How to disconnect when app did enter background

### ISSUE THREAD

**Issue by quanguyen** [daltoniam/Starscream#501]
Hi,

In my app, I want to actively disconnect from server when app enters background.

```
func applicationDidEnterBackground(_ application: UIApplication) {
        print("didEnterBackground")
        
        myws.disconnect()
    }
```

As I observe at server side, sometimes this works as expected, i.e. server recognizes the disconnection when app enters background; but sometimes **NOT**, i.e. server does not recognize **UNTIL** the app enters foreground again (and delegate `websocketDidDisconnect(socket: WebSocketClient, error: Error?)` is called).

Is there any way to make sure the connection is forced close when my app enters background?

Note that my app only enables `Background modes` for `Remote notifications`.

Regards,

**Comment by eliburke** [comment]
I'd love to know if anyone has a reliable way to guarantee this.. but I think you can never be sure with a device that can lose cellular connectivity, jump between cell and wifi, have the application force-quit, have the app crash, screen lock, etc. 
We have the best luck /w using a pretty frequent heartbeat (15-20s) on our WAMP sessions.

**Comment by daltoniam** [comment]
@eliburke is right. It is a difficult thing to guarantee since networking in general can be finicky. I think you have the right idea on disconnecting when you enter the background. You might be able to buy a bit more time using: https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtaskwithexpiratio
but again, that probably wouldn't be completely reliable. In the past, I built a message app that would do a NSURLSession request to notify the server when I was background or foreground  (for push notifications). You might be able to do that over the WebSocket too, its been a while since I've tested it. Hope that helps and best of luck!
