### ISSUE TITLE
Starscream.ErrorType.protocolError, message: "", code: 1011)

### ISSUE THREAD

**Issue by pablogeek** [daltoniam/Starscream#506]
Hello, I'm getting `Starscream.WSError(type: Starscream.ErrorType.protocolError, message: "", code: 1011))` when I try to send some data. it calls `websocketDidConnect` function first and then I try to send some text and I get this errror. Doesn't matter if I send a large message or just `"hello"`
I don't get this error everytime, I would say 30% of times.

Do you know what is happening? Any help would be appreciated! Thanks

**Comment by daltoniam** [comment]
According to the spec 1011 is:

```
1011 indicates that a server is terminating the connection because  it encountered an unexpected condition that prevented it from fulfilling the request.
```

I know that is pretty broad, but is unfortunately  the only info I can provide. I can say that isn't normal behavior so it might be something your WebSocket server doesn't like? Maybe it doesn't like or support a certain behavior? That would seem weird since Starscream is just a base RFC implementation though. Sorry I can't be more help than that, best of luck!
