### ISSUE TITLE
No delegate notification when connecting to .local domain over LTE

### ISSUE THREAD

**Issue by gdombiak** [daltoniam/Starscream#530]
Hi,

I've been using Starscream in a few projects and it works great. Thanks for this great library. :)

I'm using version **3.0.2** and noticed that when I try to connect to http://octopi.local (over mobile network) the delegate is not being triggered. It works fine if I invent an invalid http address (e.g. http://mybadaddress.com). It also works fine if I connect to a real valid address. And it works fine if I connect to http://octopi.local from my WiFi network.

Looking at the code, I see that starscream does detect the problem in this code:

        var out = timeout// wait X seconds before giving up
        FoundationStream.sharedWorkQueue.async { [weak self] in
            while !outStream.hasSpaceAvailable {
                usleep(100) // wait until the socket is ready
                out -= 100
                if out < 0 {
                    guard let s = self else {return}
                    let errCode = InternalErrorCode.writeTimeoutError.rawValue
                    completion(s.errorWithDetail("write wait timed out", code: errCode))
                    return
                } else if let error = outStream.streamError {
                    completion(error)
                    return // disconnectStream will be called.
                }
            }
            completion(nil) //success!
        }

The comment is correct in the sense that disconnectStream will be called when dealing with an invalid http address. There is no comment that disconnectStream will be called when "write wait timed out" happens which is the case when trying to connect to http://octopi.local over LTE.

The other interesting piece of information I learned is that StreamDelegate#stream:handleEvent: is being called when dealing with an invalid http address but it is NOT being called when trying to connect to http://octopi.local (over mobile network). 

Let me know if you need more info. This is a reproducible case. Just connect to a .local address over mobile network. The iPhone will timeout instead of saying that it cannot be resolved.

Thanks,
Gaston

**Comment by AlexZakharyev** [comment]
I have the same problem

**Comment by acmacalister** [comment]
Thanks for the report. How are you connecting to a `.local` `address`over a mobile network? I feel like we need to define a few things to better understand what you are seeing:

a `.local` domain meaning a domain resolved over mDNS? That means the machine is a local address on your network that probably not internet routable. That being said:

a mobile network? You mean like a LTE/4G connection? If that is the case, you aren't going to be able to resolve an address being discovered over mDNS, since that will point only to a local IP address, that the "mobile" network can not resolve or reach.
