### ISSUE TITLE
[QUESTION] Why is the WebSocket upgrade request not restricted to always create a GET request?

### ISSUE THREAD

**Issue by Sameesunkaria** [daltoniam/Starscream#623]
So, I was going through the source just to learn how the WebSocket upgrade request was created in Starscream, and I stumbled upon this line of code. 

https://github.com/daltoniam/Starscream/blob/5ecb5fd499390371a2045adeccf540b10e0ea80c/Sources/Starscream/WebSocket.swift#L615

The HTTP method of a WebSocket upgrade request should always be an HTTP `GET` request. But this line of code would allow for the request method to assume any HTTP method based on the original `URLRequest` used to initialize the `WebSocket` object. 

From the RFC 6455 standard itself,
> [The method of the request MUST be GET, and the HTTP version MUST be at least 1.1.](https://tools.ietf.org/html/rfc6455#page-17)

Is there a reason behind allowing a different HTTP method on the upgrade request (eg `POST`) that I am missing? And if not, should it be changed to always use a `GET` request irrespective of what the `URLRequest` object says.

**Comment by acmacalister** [comment]
The API for creating a connection uses `URLRequest`. Are are correct that is against the RFC and it would be a non-standard WebSocket connection if something other than GET was used. Since URLRequest opposed the method as a property, they are free to set it to what they wish, even if it doesn't follow spec. We default to GET as spec requires and this logic has been completely refactored in #653 for adding Network.framework support.
