### ISSUE TITLE
When iPhone and server stand for a few minutes without communication, onData is not called even though the server sends data

### ISSUE THREAD

**Issue by shingo-nakanishi** [daltoniam/Starscream#649]
When iPhone and server stand for a few minutes without communication, `onData` is not called even though the server sends data.

I think that it is easy to occur when the iPhone and server are in without communication for 15 to 50 minutes.

In addition, in this situation

- `isConnected` still `true`
- `onDisconnect` is not called yet.

**Comment by flagoworld** [comment]
I believe this is an issue that has been raised a number of times. This is due to a limitation with the underlying Stream and not Starscream itself. To get around this, you should issue a ping from the iPhone periodically.

If any data is written to the underlying stream while in the state you described, that stream will instantly detect that it has been disconnected, throw an error, and will allow you to restart it.

Pinging periodically does a couple of things:
1.) Prevents the stream from ever getting into the state you described above, where it is disconnected/timed out without notifying any delegates
2.) Allows you to know if the stream is hanging, timing out, etc

Every 30 seconds to 1min should suffice: `socket.write(ping: Data())`

**Comment by shingo-nakanishi** [comment]
Thank you. I try `socket.write(ping: Data())` every 20 seconds. Then this problem did not occur easily. However, it happens very rarely.
