### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by Rahulgupta-cdnsol** [daltoniam/Starscream#677]
Hi,

I am using this library for web-socket communication and able to connect with server but getting following error very frequently :
2019-07-21 19:57:30.042600+0530 Nero[2814:34333] [] nw_socket_handle_socket_event [C2034.1:1] Socket SO_ERROR [61: Connection refused]
2019-07-21 19:57:30.043500+0530 Nero[2814:34332] [] nw_connection_get_connected_socket [C2034] Client called nw_connection_get_connected_socket on unconnected nw_connection
2019-07-21 19:57:30.043989+0530 Nero[2814:34332] TCP Conn 0x600001af2280 Failed : error 0:61 [61]
websocket is disconnected: Optional("The operation couldn’t be completed. Connection refused")

Can you please look into this and let me know the solution to over the issue.

Thank you

**Comment by daltoniam** [comment]
This is going to be an issue with generic socket available and not specific to Starscream. It could be lot of different issues that are difficult to pinpoint without more knowledge into your exact setup. unfortunately that is the most help I can provide through an issue like this. Best of luck!

**Comment by dsrees** [comment]
I'm in the process of reworking the WebSocket Transport layer for [SwiftPhoenixClient](https://github.com/davidstump/SwiftPhoenixClient) and am trying to get the client's retry logic working with Starscream 4.0.4 (I dont believe it was working using Starscream 3.x so thats not related) and running into an issue with Starscream's behavior here.

My scenario is this. The Socket attempts to open a connection but the server is down or (more likely) the phone loses connection for a bit. I have logic to retry on a timed backoff however that logic is never called because the `WebSocketDelegate` does not inform the `Client` that this occurred.

I implemented the same behavior using `URLSessionWebSocketTask` by implementing [`urlSession(_:task:didCompleteWithError:)`](https://developer.apple.com/documentation/foundation/urlsessiontaskdelegate/1411610-urlsession) which is called, with an `error` when the connection was refused. Would it be possible to provide a `WebSocketEvent` that matches this behavior?

FWIW, [here is the code](https://github.com/davidstump/SwiftPhoenixClient/blob/7751dd691c6e023eb11902c9558db6c7739a8c7d/Sources/SwiftPhoenixClient/Transport.swift#L224).
