### ISSUE TITLE
Socket disconnected because of choppy connection, but it never times out, and `isConnected` returns `true`.

### ISSUE THREAD

**Issue by brunophilipe** [daltoniam/Starscream#696]
First of all, thank you for this awesome library. On to the issue:

I've been using a rather bad wifi setup for a while, and I've noticed this issue a couple of times. I don't know if this is an issue on Starscream or maybe on the underlying `URLConnection`. I've thought of building a watchdog that will disconnect and reconnect the socket if it doesn't receive data for X seconds, but I'm not sure that's the best approach.

Any thoughts?

**Comment by asif13** [comment]
Hey @brunophilipe  could this be related to [link](https://github.com/daltoniam/Starscream/issues/695)

**Comment by BaranEm** [comment]
@brunophilipe We are facing a similar issue here..

**Comment by brunophilipe** [comment]
I've worked around this by implementing a watchdog that sends a ping to the server every 30 seconds or so. If it doesn't get a pong back in 5 seconds it releases the existing socket and creates a new one.

**Comment by daltoniam** [comment]
Thanks! I appreciate the feedback. I know it has been a while since this has opened, but normally a Websocket server since a ping frame every X seconds to stimulate the connection and make sure the client is still there. The `isConnected` property was removed in the 4.0.0 release as it was racy and could return the wrong status. Ultimately choppy connections can be difficult to deal with, but with the right checks and notifications it can be worked around.

**Comment by brunophilipe** [comment]
@daltoniam 👍 Thank you for the update and for your work!
