### ISSUE TITLE
WebSocket disconnects immediately after being connected

### ISSUE THREAD

**Issue by EmmaVvv** [daltoniam/Starscream#702]
I connect to the websocket and then disconnect from it (as it's seen from server-side logs)

The delegate method is being called: 

`func websocketDidConnect(socket: WebSocketClient) {
        webSocket.write(string: "my_user_id=62")
    }`

And then it just disconnects. 

And here is my code from viewDidLoad() 

`override func viewDidLoad() {
        super.viewDidLoad()
        webSocket = WebSocket(url: URL(string: "ws://178.32.48.82:8088/")!)
        webSocket.delegate = self
        webSocket.connect()
    }`

What can be the reason? 
I don't see any logs in XCode console, but on the server-side I just get a message about disconnection.

**Comment by MaruthiBasava** [comment]
WebSocket.write() is at fault for me. My socket server would indicate that it reached an Error 1006: Abnormal closure EOF. I basically flipped my entire codebase upside down to see where it wrong and it led to the .write() to be at fail. You can even check if the write() is being properly called if it calls the completion handler. Hoping that the repo contributors fix whatever the issue is asap.

**Comment by pobengtsson** [comment]
@EmmaVvv Long time time since you opened the issue, but I am curious as it might be a similar problem that I experienced.  Did you find the cause?

**Comment by daltoniam** [comment]
I assume this is resolved now and with the release of the 4.0.0 might not be relevant anymore. If so, please reopen.
