### ISSUE TITLE
How can I judge the connect was manually closed

### ISSUE THREAD

**Issue by wsof401** [daltoniam/Starscream#715]
Hi, I read the source code and I use the delegate function 

`websocketDidDisconnect(socket: WebSocketClient, error: Error?)`

if the error is nil, I marked the connect was disconnect manually.

But sometimes, connection would be disconnect without any error.

So, How can i judge the connect was disconnect by connection error or by my own code

**Comment by daltoniam** [comment]
That will have to be monitored in your app code. Starscream doesn't know what conditions of what constitutes an intentional terminated connection or not. or not. I'd just had a flag in your code when the taps the disconnect option and then when the `websocketDidDisconnect` is called, do the appropriate logic.
