### ISSUE TITLE
CRASH or Error When connecting to a wss://host:660

### ISSUE THREAD

**Issue by luomu0371** [daltoniam/Starscream#741]
it is crash or error  in IOS11.4, iPhone6, Starscream4.0.0. but it work well in v3.1.1
error output:
Optional(Starscream.HTTPUpgradeError.notAnUpgrade(400)

![1861582611239_ pic](https://user-images.githubusercontent.com/5474804/75219937-27794480-57d9-11ea-8f8f-6fe0fa98615e.jpg)

code:
let request = URLRequest(url: url)
let security = FoundationSecurity(allowSelfSigned: true)
self.webSocket = WebSocket(request: request, certPinner: security)
self.webSocket?.delegate = self
self.webSocket?.connect()

**Comment by svmakarov** [comment]
We have the same problem do you have some ideas or workarounds?

**Comment by daltoniam** [comment]
sorry I can't help without more context, but it appears to be returning a 400 error instead of the expected 101 error. I might suggest upgrading to the 4.0.1 version as it change a bit of the SSL validation code since others where having problems with it. If the problem persist, please feel free to reopen this issue with some more debugging information. Thanks!
