### ISSUE TITLE
Why NativeEngine is commented ?

### ISSUE THREAD

**Issue by StevenWatremez** [daltoniam/Starscream#744]
I checked some news about Starscream and I saw that you worked on Native websocket implementation  in addition to your websocket. So I found that you have a Native Engine class https://github.com/daltoniam/Starscream/blob/4.0.0/Sources/Engine/NativeEngine.swift

but this file is commented and the caller too : 
`//TODO: will release once Xcode 11 is out of beta`

And Xcode 11 was released in September, so any news about this integration ? Have you some problem with the native api ?

**Comment by NghiaTranUIT** [comment]
Look like this repo is not maintained by the authors anymore.

Btw, it's reasonable to use `URLSessionWebSocketTask` since we need to write the WebSocket Parse.

**Comment by StevenWatremez** [comment]
Ok thanks. I will check this.

**Comment by michalcichon** [comment]
@daltoniam I believe you still maintain this library? Can you elaborate a bit about what do you plan?

**Comment by daltoniam** [comment]
It was originally comment off because the API was broken in the beta (crashed when connecting to my local testing server). It has now since been fixed and I enabled it in the 4.0.1 release, which I just pushed to CocoaPods. It will default to the native API if the API is supported on that version/platform.

https://github.com/daltoniam/Starscream/blob/master/Sources/Starscream/WebSocket.swift#L124
