### ISSUE TITLE
Cannot connect to secure wss:// websocket on iOS 11 & earlier

### ISSUE THREAD

**Issue by nickdowell** [daltoniam/Starscream#748]
The `FoundationTransport` (used on iOS 11 & earlier) does not establish a secure connection to the host, resulting in a failed connection to hosts that require security.

The following code snippet replicates the problem on all platforms by forcing use of the `FoundationTransport`

```swift
import Starscream

class WebsocketTester: WebSocketDelegate {
    
    var webSocket: WebSocket?
    
    func start() {
        let url = URL(string: "wss://echo.websocket.org")!
        webSocket = WebSocket(request: URLRequest(url: url), engine:
            WSEngine(transport: FoundationTransport(), certPinner: FoundationSecurity()))
        webSocket?.delegate = self
        webSocket?.connect()
    }
    
    func didReceive(event: WebSocketEvent, client: WebSocket) {
        print(#function, event)
    }
}
```

The output of running this is

```
didReceive(event:client:) cancelled
```

This has previously been reported in https://github.com/daltoniam/Starscream/issues/728

**Comment by jaltreuter** [comment]
@nickdowell thank you for putting up that pull request.  This same issue started happening in my app after upgrading from Starscream 3.0.5 to 4.0.0.  I ended up simply making a copy of FoundationTransport and adding your changes, and that was effective at solving the problem.

I'd love to see this get some attention from the devs, since it's easily reproducible and affects a reasonably large audience.
