### ISSUE TITLE
Warnings with Xcode 11.4 - Initialization of 'UnsafeMutablePointer<UInt8>' results in a dangling pointer

### ISSUE THREAD

**Issue by tfonfara** [daltoniam/Starscream#758]
See title of the issue, WSCompression.swift states two warnings that the initialization of 'UnsafeMutablePointer<UInt8>' results in a dangling pointer.

Further info from Xcode:
1. Implicit argument conversion from '[UInt8]' to 'UnsafeMutablePointer<UInt8>' produces a pointer valid only for the duration of the call to 'init(_:)'
2. Use the 'withUnsafeMutableBufferPointer' method on Array in order to explicitly convert argument to buffer pointer valid for a defined scope

**Comment by VTCoco** [comment]
Xcode 11.4 with Starscream 3.1.0 cause a crash on my side in release mode (due to Swift optimisation) at initialization of `socket = WebSocket(request: request)` on **iOS 10** & **iOS 9**, so 32bits devices.

https://www.reddit.com/r/iOSProgramming/comments/frcpsc/xcode_114_builds_crashes_on_ios_10/
https://forums.swift.org/t/crashes-on-32-bit-after-xcode-11-4/35035/5
https://bugs.swift.org/browse/SR-12511

**Comment by rudyrichter** [comment]
See https://github.com/daltoniam/Starscream/pull/766 for fix

**Comment by daltoniam** [comment]
4.0.4 released!
