### ISSUE TITLE
How to pass parameters to get data from WebSocket, I was able to connect to socket but not getting data from socket

### ISSUE THREAD

**Issue by sairushi-gloify** [daltoniam/Starscream#774]

**Comment by aaksh-acto** [comment]
var request = URLRequest(url: URL(string: "wss://base_url?access_token=\(AccessToken)&param1=\(valueForParam1)")!)
                  request.timeoutInterval = 20
                  socket = WebSocket(request: request)
                  socket.delegate = self
                  socket.connect()

**Comment by aaksh-acto** [comment]
1. Add "WebSocketDelegate" to your chat view controller class
e.g. ` class ChatViewController: WebSocketDelegate{
}`
Create `var isSocketConnected = false`

// To pass parameters use the below request var 
**`var request = URLRequest(url: URL(string: "wss://base_url?access_token=(AccessToken)&param1=(valueForParam1)")!)**
request.timeoutInterval = 20
socket = WebSocket(request: request)
socket.delegate = self
socket.connect()`

`socket = WebSocket(request: request)
socket.delegate = self
socket.connect() // to connect
socket.disconnect()`
// in the did receive method .cancelled case will be called instead of .disconnect

Implement the below function: 
```
func didReceive(event: WebSocketEvent, client: WebSocket) {
        switch event {
        case .connected(let headers):
             isSocketConnected = true
           // socket is connected
            print("websocket is connected: \(headers)")
             self.chatTextField.text = "websocket is connected"
        case .disconnected(let reason, let code):
            isSocketConnected = false
           //Socket is disconnected
            print("websocket is disconnected: \(reason) with code: \(code)")
        case .text(let responseString):
               print(responseString)
       case .binary(let data):
            print("Received data: \(data.count)")
        case .ping(_):
            break
        case .pong(_):
            break
        case .viabilityChanged(_):
            break
        case .reconnectSuggested(_):
            break
        case .cancelled:
            print("-------------------")
            print("Websocket is Cancelled")
            print("-------------------")
            isSocketConnected = false
        case .error(let error):
            isSocketConnected = false
            handleError(error)
            
        }
    }

```
