### ISSUE TITLE
WebSocket connect failed in WatchOS9 beta device, with error"unsatisfied (Path was denied by NECP policy"

### ISSUE THREAD

**Issue by alviet** [daltoniam/Starscream#957]
Hi Dalton, 
Thanks for your great work.
I got below issue. Please take a look.

Issue: 
- Error log:
Native engine: 
`[C6.1 Hostname#xx:443 waiting path (unsatisfied (Path was denied by NECP policy), interface: ipsec1, ipv4, ipv6, proxy)] event: path:unsatisfied @0.004s, uuid: xxx`
Custom engine:
`[C1 mymachine.com:443 waiting parent-flow (unsatisfied (Path was denied by NECP policy), interface: ipsec2, ipv4, ipv6, proxy)] event: path:unsatisfied @0.002s, uuid: xxx`

- Note: 
1. No error found in simulator WatchOS 9 same beta, but just real device as descibed
2. Current project works fine with WatchOS 7~8.7 both simulator and device
3. I tried Starscream tags 4.0.0, and 4.0.1, 4.0.4 already, same result
4. The Watch device is paired with iOS16 beta5 iPhone

If you need more information in detail, please let me know.

Regards.

**Comment by dfed** [comment]
In case it's helpful, I'm seeing this same error on a real device on production watchOS 9.0 using a `NWConnection`. My app works fine on watchOS 6, 7, and 8.

**Comment by dfed** [comment]
Following up: I've gotten confirmation from Apple's developer support team that the NECP policy denial is expected per [this post in the dev forums](https://developer.apple.com/forums/thread/127232). That NECP policy allowed web sockets on watchOS unrelated to audio sessions prior to watchOS 9 was unfortunately a bug that Apple fixed in watchOS 9 (mentioning it in the release notes would have been nice!).

As such, I think Starscream is behaving correctly here, and I recommend closing this issue.

**Comment by alviet** [comment]
Thanks for your kindly support. It is good to hear Starscream doing good.
As the fixes of Apple, I stop using Websocket to use REST API on WatchApp.
